# -*- coding: utf-8 -*-
"""СБОРКА ПАКЕТА ДЛЯ arXiv. Пишет arxiv/: audit.tex, generator.tex, fig/*.tex,
SUBMIT.md с чеклистом.

Ограничение назвать прямо: на машине НЕТ ни LaTeX, ни pandoc, поэтому проверить
компиляцией нельзя. Вместо этого в конце — СИНТАКСИЧЕСКАЯ проверка: баланс
скобок и окружений, наличие всех \\input, отсутствие голых спецсимволов и
непереведённых юникодных знаков. Она не заменяет компиляцию и об этом говорит.
"""
import re, os, sys, subprocess, collections
sys.path.insert(0, "scripts")
from md2tex import convert, esc, inline

OUT = "arxiv"
os.makedirs(OUT, exist_ok=True)

PREAMBLE = r"""%% Generated by scripts/build_arxiv.py -- edit the .md sources, not this file.
\documentclass[11pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[margin=1in]{geometry}
\usepackage{booktabs}
\usepackage{tikz}
\usepackage{microtype}
\usepackage[hidelinks]{hyperref}
\setlength{\parskip}{0.5em}
\setlength{\parindent}{0pt}
\renewcommand{\arraystretch}{1.1}
\title{%(title)s}
\author{%(author)s}
\date{%(date)s}
\begin{document}
\maketitle
"""

AUTHOR = r"\textbf{[AUTHOR NAME -- fill in]}\\\textbf{[affiliation, or state there is none]}\\\texttt{[e-mail]}"
DATE = "4 September 2026"

def split_front(md):
    """заголовок, преамбульные курсивы, аннотация, тело"""
    lines = md.split("\n")
    title = lines[0].lstrip("# ").strip()
    try:  a = lines.index("## Abstract")
    except ValueError: a = None
    try:  r = lines.index("## References")
    except ValueError: r = len(lines)
    head = "\n".join(lines[1:a])
    nxt = next(k for k in range(a + 1, len(lines)) if lines[k].startswith("## "))
    abstract = "\n".join(lines[a + 1:nxt]).strip()
    body = "\n".join(lines[nxt:r])
    refs = [l.strip() for l in lines[r + 1:] if l.strip()]
    return title, head, abstract, body, refs

def build(src, out, title_override=None):
    md = open(src, encoding="utf-8").read()
    title, head, abstract, body, refs = split_front(md)
    t = [PREAMBLE % dict(title=esc(title), author=AUTHOR, date=DATE)]
    t.append(r"\begin{abstract}" + "\n" + convert(abstract).strip() + "\n" + r"\end{abstract}" + "\n")
    if head.strip():
        t.append(r"\begin{center}\small\itshape" + "\n" + convert(head).strip() + "\n" + r"\end{center}" + "\n")
    t.append(convert(body))
    if refs:
        t.append(r"\section*{References}" + "\n")
        for line in refs:
            t.append(r"\noindent\hangindent=1.5em " + convert(line).strip() + r"\par")
        t.append("")
    t.append(r"\end{document}" + chr(10))
    open(f"{OUT}/{out}", "w", encoding="utf-8").write("\n".join(t))
    return out

# ── синтаксическая проверка (компиляции нет) ────────────────────────────────
def check(path):
    t = open(path, encoding="utf-8").read()
    bad = []
    if t.count("{") != t.count("}"):
        bad.append(f"скобки не сходятся: {{ {t.count('{')} против }} {t.count('}')}")
    envs = collections.Counter(re.findall(r"\\begin\{(\w+\*?)\}", t))
    ends = collections.Counter(re.findall(r"\\end\{(\w+\*?)\}", t))
    for e in set(envs) | set(ends):
        if envs[e] != ends[e]: bad.append(f"окружение {e}: begin {envs[e]}, end {ends[e]}")
    for m in re.finditer(r"\\input\{([^}]+)\}", t):
        if not os.path.exists(f"{OUT}/{m.group(1)}"): bad.append(f"нет файла {m.group(1)}")
    # непереведённый юникод вне tikz-цветов
    # диакритика латиницы (Janečková, Dostál) при T1+utf8 законна; ловим ЧУЖИЕ письменности
    left = set(re.findall(r"[^\x00-\x7F]", t)) - set("áàâäãéèêëíìîïóòôöõúùûüñçčšžřýůěďťň")
    if left: bad.append(f"знаки вне латиницы: {' '.join(sorted(left))}")
    # голые спецсимволы вне команд
    for ch in "%#":                    # & — разделитель колонок, здесь он законен
        n = len(re.findall(rf"(?<!\\){re.escape(ch)}", t))
        if ch == "%": n -= len(re.findall(r"^%", t, re.M))
        if n: bad.append(f"неэкранированных «{ch}»: {n}")
    # таблицы: одинаковое ли число & в строках
    for blk in re.findall(r"\\begin\{tabular\}\{@\{\}(\w+)@\{\}\}(.*?)\\end\{tabular\}", t, re.S):
        cols = len(blk[0])
        for row in [r for r in blk[1].split(r"\\") if "&" in r]:
            k = len(re.findall(r"(?<!\\)&", row)) + 1   # \& внутри ячейки — не разделитель
            if k != cols:
                bad.append(f"строка таблицы на {k} полей при {cols} колонках: {row.strip()[:48]}")
    return bad

def submit_md(files):
    """чеклист подачи РЯДОМ с пакетом и с живыми числами — руками он терялся при
    чистой пересборке (make arxiv сносит каталог целиком)"""
    src = open("SUBMIT-template.md", encoding="utf-8").read()
    figs = sorted(f for f in os.listdir(f"{OUT}/fig") if f.endswith(".tex"))
    holes = []
    for f in files:
        t = open(f"{OUT}/{f}", encoding="utf-8").read()
        holes += [f"{f}: {m}" for m in re.findall(r"\[[^\]]*?(?:fill in|there is none|e-mail|ORCID)[^\]]*\]", t)]
    inv = "\n".join(f"    {f}" for f in files + [f"fig/{x}" for x in figs])
    open(f"{OUT}/SUBMIT.md", "w", encoding="utf-8").write(
        src.replace("<<FILES>>", inv).replace("<<HOLES>>", "\n".join(f"      - `{h}`" for h in holes)))

if __name__ == "__main__":
    subprocess.run([sys.executable, "scripts/figures_tex.py"], check=True)
    files = [build("paper-audit.md", "audit.tex"),
             build("paper-generator.md", "generator.tex")]
    submit_md(files)
    print("\nСИНТАКСИЧЕСКАЯ ПРОВЕРКА (компиляции нет — LaTeX на машине не установлен)")
    fail = 0
    for f in files:
        b = check(f"{OUT}/{f}")
        print(f"  {f}: {'чисто' if not b else str(len(b))+' замечаний'}")
        for x in b[:12]: print(f"      · {x}")
        fail += len(b)
    print(f"\n{'ЗАМЕЧАНИЙ НЕТ' if not fail else f'ЗАМЕЧАНИЙ: {fail}'}")
    sys.exit(1 if fail else 0)
