# -*- coding: utf-8 -*-
"""ФИГУРЫ ДЛЯ ДВУХ СТАТЕЙ. Пишет отдельные SVG в img/fig/.

Числа берутся из data/paper_numbers.json там, где они в манифесте, — тогда
scripts/check_paper.py держит фигуру и текст в согласии. Остальные приведены
здесь с указанием скрипта, который их посчитал: это результаты решёточных
прогонов, которые в манифест не влезают по времени.

Цвета заданы под белый лист (arXiv печатает PDF), без внешних шрифтов.
"""
import json, os, math, sys

OUT = "img/fig"
os.makedirs(OUT, exist_ok=True)
NUM = {}
if os.path.exists("data/paper_numbers.json"):
    NUM = {r["key"]: r["value"] for r in json.load(open("data/paper_numbers.json", encoding="utf-8"))}
def n(key, fallback):
    """число из манифеста, иначе запасное (с предупреждением)"""
    if key in NUM: return NUM[key]
    print(f"  ! {key} нет в манифесте, беру запасное {fallback}", file=sys.stderr)
    return fallback

INK   = "#1a1a1a"
INK2  = "#5a5a5a"
INK3  = "#8a8a8a"
RULE  = "#d0d0d0"
FILL  = "#2b2b2b"      # рукопись
FILL2 = "#9a9a9a"      # языки / первое выравнивание
FILL3 = "#c8c8c8"      # второе выравнивание
FONT  = "Helvetica, Arial, sans-serif"
MONO  = "'DejaVu Sans Mono', Menlo, monospace"

def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))

class Svg:
    def __init__(self, w, h):
        self.w, self.h, self.p = w, h, []
    def txt(self, x, y, s, size=11, fill=INK, anchor="start", weight="normal", font=FONT, dy=0):
        self.p.append(f'<text x="{x:.1f}" y="{y+dy:.1f}" font-family="{font}" font-size="{size}" '
                      f'fill="{fill}" text-anchor="{anchor}" font-weight="{weight}">{esc(s)}</text>')
    def rect(self, x, y, w, h, fill=FILL, op=1.0):
        if w <= 0 or h <= 0: return
        self.p.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" fill="{fill}" opacity="{op}"/>')
    def line(self, x1, y1, x2, y2, stroke=RULE, w=1, dash=None):
        d = f' stroke-dasharray="{dash}"' if dash else ""
        self.p.append(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
                      f'stroke="{stroke}" stroke-width="{w}"{d}/>')
    def path(self, pts, stroke=FILL, w=1.6, dash=None):
        d = "M " + " L ".join(f"{x:.1f} {y:.1f}" for x, y in pts)
        da = f' stroke-dasharray="{dash}"' if dash else ""
        self.p.append(f'<path d="{d}" fill="none" stroke="{stroke}" stroke-width="{w}"{da}/>')
    def dot(self, x, y, r=3.5, fill=FILL):
        self.p.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" fill="{fill}"/>')
    def save(self, name, title):
        head = (f'<svg xmlns="http://www.w3.org/2000/svg" width="{self.w}" height="{self.h}" '
                f'viewBox="0 0 {self.w} {self.h}"><title>{esc(title)}</title>'
                f'<rect width="{self.w}" height="{self.h}" fill="#ffffff"/>')
        open(f"{OUT}/{name}.svg", "w", encoding="utf-8").write(head + "".join(self.p) + "</svg>")
        print(f"  {OUT}/{name}.svg")

# ── фиг. 1: перерождение цепи, ДВА выравнивания ─────────────────────────────
def fig1():
    s = Svg(560, 372)
    voy = n("regen_voy_head", 28.8)
    rows = [("Voynichese", voy, None),
            ("Italian",  n("regen_ita_meanlen", 5.9),  n("regen_ita_lendist", 6.6)),
            ("Spanish",  n("regen_spa_meanlen", 2.6),  n("regen_spa_lendist", 5.7)),
            ("Latin",    n("regen_lat_meanlen", 1.7),  n("regen_lat_lendist", 3.5))]
    x0, y0, bw, gap = 132, 58, 300, 52
    mx = 32.0
    s.txt(0, 18, "Chain regeneration of the vocabulary", 13, INK, weight="600")
    s.txt(0, 34, "share of words generated by a second-order character chain that are real types",
          10.5, INK2)
    for i in range(0, 35, 10):
        x = x0 + bw * i / mx
        s.line(x, y0 - 8, x, y0 + gap * 4 - 22, RULE if i else INK3)
        s.txt(x, y0 + gap * 4 - 8, f"{i}%", 9.5, INK3, anchor="middle")
    for i, (lab, a, b) in enumerate(rows):
        y = y0 + gap * i
        s.txt(x0 - 10, y + 9, lab, 11, INK, anchor="end")
        if b is None:
            s.rect(x0, y, bw * a / mx, 22, FILL)
            s.txt(x0 + bw * a / mx + 6, y + 15, f"{a:.1f}%", 11, INK, weight="600")
        else:
            s.rect(x0, y - 2, bw * a / mx, 13, FILL2)
            s.rect(x0, y + 13, bw * b / mx, 13, FILL3)
            s.txt(x0 + bw * a / mx + 5, y + 8, f"{a:.1f}%", 9.5, INK2)
            s.txt(x0 + bw * b / mx + 5, y + 23, f"{b:.1f}%", 9.5, INK2)
    ly = y0 + gap * 4 + 14
    s.rect(x0, ly, 13, 11, FILL2); s.txt(x0 + 18, ly + 9, "matched on mean type length", 10, INK2)
    s.rect(x0, ly + 16, 13, 11, FILL3); s.txt(x0 + 18, ly + 25, "matched on the whole length distribution", 10, INK2)
    s.txt(x0 - 10, ly + 17, "controls", 10, INK3, anchor="end")
    s.txt(0, ly + 52, "All sub-vocabularies are 7,205 types. The gap is 4–17× depending on which matching is used.",
          10, INK3)
    s.save("fig1-regeneration", "Chain regeneration under two matchings")

# ── фиг. 2: типы против токенов по длине слова ──────────────────────────────
def fig2():
    # scripts/typetoken2.py
    L   = [3, 4, 5, 6, 7]
    tok = [2.03, 4.52, 5.76, 4.50, 3.20]
    typ = [2.48, 2.43, 1.55, 1.98, 1.60]
    s = Svg(560, 300)
    x0, y0, w, h = 62, 62, 420, 175
    s.txt(0, 18, "Slot rigidity: the gap with Latin depends on the unit", 13, INK, weight="600")
    s.txt(0, 34, "excess of glyph–position mutual information over a within-word shuffle, Voynichese ÷ Latin",
          10.5, INK2)
    mx = 6.0
    for v in range(1, 7):
        y = y0 + h - h * (v - 1) / (mx - 1)
        s.line(x0, y, x0 + w, y, RULE if v > 1 else INK3)
        s.txt(x0 - 8, y + 3.5, f"{v}×", 9.5, INK3, anchor="end")
    px = lambda i: x0 + w * i / (len(L) - 1)
    py = lambda v: y0 + h - h * (v - 1) / (mx - 1)
    for i, v in enumerate(L):
        s.txt(px(i), y0 + h + 18, str(v), 10, INK2, anchor="middle")
    s.txt(x0 + w / 2, y0 + h + 36, "word length (characters)", 10, INK3, anchor="middle")
    s.path([(px(i), py(v)) for i, v in enumerate(tok)], FILL, 1.8)
    s.path([(px(i), py(v)) for i, v in enumerate(typ)], INK3, 1.8, dash="5 3")
    for i, v in enumerate(tok): s.dot(px(i), py(v), 3.5, FILL)
    for i, v in enumerate(typ): s.dot(px(i), py(v), 3.5, INK3)
    s.txt(px(3) + 10, py(tok[3]) - 6, "measured on tokens", 10.5, INK, weight="600")
    s.txt(px(3) + 10, py(typ[3]) + 16, "measured on types", 10.5, INK2)
    # отметить переворот на длине 3
    s.line(px(0), py(typ[0]) - 12, px(0), py(tok[0]) + 12, INK3, 1, dash="2 2")
    s.txt(px(0) + 6, y0 + 14, "at length 3", 9.5, INK3)
    s.txt(px(0) + 6, y0 + 26, "the order reverses", 9.5, INK3)
    s.save("fig2-type-token", "Type versus token by word length")

# ── фиг. 3: одна величина, три алгоритма ───────────────────────────────────
def fig3():
    # scripts/one_instrument.py, scripts/morf_spread.py
    rows = [("1  affix + vocabulary word", -15.83, None),
            ("2  Goldsmith signatures",     -1.02, None),
            ("3  Morfessor Baseline",      -10.82, (-11.26, -10.18))]
    s = Svg(560, 330)
    x0, y0, w, gap = 210, 66, 265, 44
    s.txt(0, 18, "One quantity, three decompositions", 13, INK, weight="600")
    s.txt(0, 34, "shift in type-level slot rigidity after stripping affixes (manuscript, ZL3b, length 4)",
          10.5, INK2)
    lo, hi = -18.0, 1.0
    px = lambda v: x0 + w * (v - lo) / (hi - lo)
    for v in (-15, -10, -5, 0):
        s.line(px(v), y0 - 10, px(v), y0 + gap * 3 - 20, INK3 if v == 0 else RULE)
        s.txt(px(v), y0 + gap * 3 - 6, str(v).replace("-", "\u2212"), 9.5, INK3, anchor="middle")
    for i, (lab, v, spread) in enumerate(rows):
        y = y0 + gap * i
        s.txt(x0 - 12, y + 8, lab, 11, INK, anchor="end", font=FONT)
        if spread:
            s.rect(px(spread[0]), y - 3, px(spread[1]) - px(spread[0]), 14, FILL3)
            s.line(px(spread[0]), y - 3, px(spread[0]), y + 11, INK3, 1.2)
            s.line(px(spread[1]), y - 3, px(spread[1]), y + 11, INK3, 1.2)
        s.line(px(0), y + 4, px(v), y + 4, FILL, 2.2)
        s.dot(px(v), y + 4, 4, FILL)
        lbl = f"{v:+.2f}".replace("-", "\u2212")
        # подпись справа от точки, если она у левого края — иначе налезает на имя строки
        if px(v) < x0 + w * 0.25: s.txt(px(v) + 10, y - 6, lbl, 10.5, INK, weight="600")
        else: s.txt(px(v) - 10, y + 8, lbl, 10.5, INK, anchor="end", weight="600")
    s.txt(x0 - 12, y0 + gap * 3 + 16, "spread over five seeds", 9.5, INK3, anchor="end")
    s.rect(x0, y0 + gap * 3 + 6, 24, 12, FILL3)
    s.txt(0, y0 + gap * 3 + 44,
          "Morfessor has no seed of its own; its row is a mean of five runs, and Latin's own shift changes sign between them.",
          10, INK3)
    s.txt(0, y0 + gap * 3 + 58,
          "The spread between algorithms is the finding: no single number should be quoted without the procedure.",
          10, INK3)
    s.save("fig3-three-algorithms", "One quantity, three decompositions")

# ── фиг. 4: прогрессия архитектур по стыку ─────────────────────────────────
def fig4():
    # scripts/construct*.py, scripts/threshold.py
    rows = [("selection of whole words", "503 grid points", 26),
            ("hybrid: memory ignores the boundary", "construction + memory", 41),
            ("memory filtered for legality", "27 configurations", 55),
            ("memory weighted by transition frequency", "54 configurations", 82)]
    s = Svg(560, 292)
    x0, y0, w, gap = 250, 62, 220, 42
    s.txt(0, 18, "Reaching the word-boundary information", 13, INK, weight="600")
    s.txt(0, 34, "best three-character junction attained while the other three signatures are held",
          10.5, INK2)
    for v in (0, 25, 50, 75, 100):
        s.line(x0 + w * v / 100, y0 - 10, x0 + w * v / 100, y0 + gap * 4 - 18, RULE if v else INK3)
        s.txt(x0 + w * v / 100, y0 + gap * 4 - 4, f"{v}%", 9.5, INK3, anchor="middle")
    for i, (lab, sub, v) in enumerate(rows):
        y = y0 + gap * i
        last = i == len(rows) - 1
        s.txt(x0 - 12, y + 6, lab, 11, INK, anchor="end", weight="600" if last else "normal")
        s.txt(x0 - 12, y + 19, sub, 9.5, INK3, anchor="end")
        s.rect(x0, y - 2, w * v / 100, 17, FILL if last else FILL2)
        s.txt(x0 + w * v / 100 + 6, y + 11, f"{v}%", 11, INK, weight="600" if last else "normal")
    s.txt(0, y0 + gap * 4 + 24,
          "Filtering preserves which boundary transitions are possible; weighting preserves their frequencies.",
          10, INK3)
    s.txt(0, y0 + gap * 4 + 38,
          "The junction lives in the distribution, not in its support — which is what the 55 → 82 step shows.",
          10, INK3)
    s.save("fig4-architectures", "Reaching the word-boundary information")

# ── фиг. 5: порог был несущим ──────────────────────────────────────────────
def fig5():
    # scripts/threshold.py
    th = [(65, 23), (70, 18), (75, 6), (80, 2), (85, 0)]
    s = Svg(560, 300)
    x0, y0, w, h = 62, 62, 420, 150
    s.txt(0, 18, "The threshold was load-bearing", 13, INK, weight="600")
    s.txt(0, 34, "configurations of 54 reaching all four signatures, by the threshold called “reached”",
          10.5, INK2)
    mx = 24
    for v in (0, 6, 12, 18, 24):
        y = y0 + h - h * v / mx
        s.line(x0, y, x0 + w, y, RULE if v else INK3)
        s.txt(x0 - 8, y + 3.5, str(v), 9.5, INK3, anchor="end")
    bw = w / len(th) * 0.5
    for i, (t, c) in enumerate(th):
        x = x0 + w * (i + 0.5) / len(th) - bw / 2
        y = y0 + h - h * c / mx
        s.rect(x, y, bw, h * c / mx, FILL if t == 70 else FILL2)
        s.txt(x + bw / 2, y - 7, str(c), 11, INK, anchor="middle", weight="600" if t == 70 else "normal")
        s.txt(x + bw / 2, y0 + h + 18, f"{t}%", 10.5, INK if t == 70 else INK2, anchor="middle",
              weight="600" if t == 70 else "normal")
    s.txt(x0 + w / 2, y0 + h + 36, "threshold declared in advance", 10, INK3, anchor="middle")
    s.txt(0, y0 + h + 60,
          "Stated without a threshold: the best worst-of-four ratio anywhere on the grid is 82%, with a median of 58%.",
          10, INK3)
    s.save("fig5-threshold", "The threshold was load-bearing")

# ── фиг. 6: расхождение начала строки по знакам ────────────────────────────
def fig6():
    # scripts/line_residual.py, scripts/line_null2.py
    data = [("d", 15.4, 8.4, 12.7), ("s", 14.7, 11.7, 11.8), ("y", 14.7, 3.5, 8.2),
            ("o", 13.6, 21.4, 17.9), ("q", 13.0, 15.9, 15.8), ("t", 9.7, 1.9, 5.3),
            ("p", 9.3, 0.5, 3.9), ("c", 3.7, 20.4, 12.2), ("a", 0.4, 6.0, 3.7)]
    s = Svg(560, 322)
    x0, y0, h, gap = 52, 74, 150, 0
    s.txt(0, 18, "What prepending does not account for at the line start", 13, INK, weight="600")
    s.txt(0, 34, "first character of the first word of a line, against mid-line words and against a",
          10.5, INK2)
    s.txt(0, 48, "prepending-only model at the rate the observed length gain implies (p = 0.40)", 10.5, INK2)
    mx = 23.0
    cw = (520 - x0) / len(data)
    for v in (0, 5, 10, 15, 20):
        y = y0 + h - h * v / mx
        s.line(x0, y, 520, y, RULE if v else INK3)
        s.txt(x0 - 8, y + 3.5, f"{v}%", 9.5, INK3, anchor="end")
    for i, (ch, obs, mid, pred) in enumerate(data):
        cx = x0 + cw * (i + 0.5)
        s.rect(cx - 14, y0 + h - h * obs / mx, 13, h * obs / mx, FILL)
        s.rect(cx + 1, y0 + h - h * mid / mx, 13, h * mid / mx, FILL3)
        s.line(cx - 16, y0 + h - h * pred / mx, cx + 16, y0 + h - h * pred / mx, INK, 1.8, dash="3 2")
        s.txt(cx, y0 + h + 18, ch, 11.5, INK, anchor="middle", font=MONO)
        r = obs - pred
        if abs(r) >= 4:
            s.txt(cx, y0 + h + 34, f"{r:+.0f}", 9.5, INK2, anchor="middle")
    s.txt(x0, y0 + h + 34, "residual", 9.5, INK3, anchor="end")
    ly = y0 + h + 54
    s.rect(x0, ly, 13, 11, FILL);  s.txt(x0 + 18, ly + 9, "line-initial", 10, INK2)
    s.rect(x0 + 100, ly, 13, 11, FILL3); s.txt(x0 + 118, ly + 9, "mid-line", 10, INK2)
    s.line(x0 + 190, ly + 6, x0 + 212, ly + 6, INK, 1.8, dash="3 2")
    s.txt(x0 + 218, ly + 9, "predicted by prepending alone", 10, INK2)
    s.txt(0, ly + 34,
          "Prepending at the rate its own length signature implies produces a divergence of 0.186 against the observed 0.385.",
          10, INK3)
    s.save("fig6-line-start", "What prepending does not account for")

print("фигуры:")
for f in (fig1, fig2, fig3, fig4, fig5, fig6): f()
# страница для просмотра всех сразу
idx = ['<title>Figures</title><style>body{font:14px Helvetica,Arial,sans-serif;max-width:640px;'
       'margin:40px auto;padding:0 16px;color:#222}img{width:100%;border:1px solid #e0e0e0;'
       'margin:8px 0 28px}h1{font-size:19px}code{background:#f4f4f4;padding:1px 4px}</style>',
       "<h1>Figures for both papers</h1>",
       "<p>Generated by <code>scripts/figures.py</code>. Numbers come from "
       "<code>data/paper_numbers.json</code> where the manifest covers them, so "
       "<code>make check</code> keeps figure and text in agreement.</p>"]
for f in ("fig1-regeneration", "fig2-type-token", "fig3-three-algorithms",
          "fig4-architectures", "fig5-threshold", "fig6-line-start"):
    idx.append(f'<p><code>{f}.svg</code></p><img src="{f}.svg" alt="{f}">')
open(f"{OUT}/index.html", "w", encoding="utf-8").write("\n".join(idx))
print(f"  {OUT}/index.html")
